## -----------------------------------------------
## Basic Configuration
## -----------------------------------------------
baseurl = "http://rnr-t2c.github.io"
title = "Talk2Car-RegSeg dataset"
theme = "hugo-story"
publishdir = "rnr-t2c.github.io"

## -----------------------------------------------
## Hugo Built-in Features
## -----------------------------------------------

disableKinds = ["taxonomy", "taxonomyTerm", "section"]
# googleAnalytics = "your-google-analytics-id"


## -----------------------------------------------
## Site Parameters
## -----------------------------------------------

[Params]
  description = "Talk2Car-RegSeg dataset"
  logo = "images/banner1.png"
  favicon = true

[Params.social]
  github = "https://github.com/rnr-t2c"
